import { useState, type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { Plus, Trash2 } from 'lucide-react'
import { useTravels } from '@/hooks/useTransversal'
import { formatCurrency } from '@/lib/utils'
import type { CreateTravelInput, TravelItem } from '@/types'

const statuses: TravelItem['status'][] = ['solicitada', 'aprovada', 'realizada', 'cancelada']

export default function TravelsPage() {
  const { projectId } = useParams()
  const { items, estimated, actual, isLoading, create, update, remove } = useTravels(projectId)
  const [draft, setDraft] = useState<Partial<CreateTravelInput>>({ status: 'solicitada' })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); create.mutate({ traveler: draft.traveler ?? '', destination: draft.destination, departure_date: draft.departure_date, return_date: draft.return_date, purpose: draft.purpose, estimated_cost: Number(draft.estimated_cost ?? 0), actual_cost: Number(draft.actual_cost ?? 0), status: draft.status ?? 'solicitada', notes: draft.notes }, { onSuccess: () => setDraft({ status: 'solicitada' }) }) }
  return <div className="mx-auto max-w-7xl px-6 py-8"><header className="mb-6"><span className="badge badge-blue">Módulo transversal</span><h1 className="mt-3 text-2xl font-bold text-text-primary">Viagens</h1><p className="mt-1 text-sm text-text-secondary">Estimado {formatCurrency(estimated)} - Real {formatCurrency(actual)}</p></header><form className="card mb-5" onSubmit={submit}><div className="grid gap-4 md:grid-cols-6"><Input label="Viajante" value={draft.traveler ?? ''} onChange={(traveler) => setDraft((d) => ({ ...d, traveler }))} /><Input label="Destino" value={draft.destination ?? ''} onChange={(destination) => setDraft((d) => ({ ...d, destination }))} /><Input label="Saída" type="date" value={draft.departure_date ?? ''} onChange={(departure_date) => setDraft((d) => ({ ...d, departure_date }))} /><Input label="Retorno" type="date" value={draft.return_date ?? ''} onChange={(return_date) => setDraft((d) => ({ ...d, return_date }))} /><Select value={draft.status ?? 'solicitada'} onChange={(status) => setDraft((d) => ({ ...d, status: status as TravelItem['status'] }))} /><button className="btn-primary self-end" type="submit"><Plus className="h-4 w-4" /> Criar</button></div></form><section className="card overflow-hidden p-0">{isLoading ? <div className="p-6 text-text-secondary">Carregando...</div> : <table className="data-table"><thead><tr><th>Viajante</th><th>Destino</th><th>Saída</th><th>Retorno</th><th>Motivo</th><th>Custo Est.</th><th>Custo Real</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td className="text-text-primary">{item.traveler}</td><td>{item.destination ?? '-'}</td><td>{item.departure_date ?? '-'}</td><td>{item.return_date ?? '-'}</td><td>{item.purpose ?? '-'}</td><td>{formatCurrency(item.estimated_cost ?? 0)}</td><td>{formatCurrency(item.actual_cost ?? 0)}</td><td><Select compact value={item.status} onChange={(status) => update.mutate({ itemId: item.id, input: { status: status as TravelItem['status'] } })} /></td><td><button className="btn-danger btn-sm" type="button" onClick={() => remove.mutate(item.id)}><Trash2 className="h-3.5 w-3.5" /></button></td></tr>)}</tbody></table>}</section></div>
}
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; type?: string; onChange: (value: string) => void }) { return <label><span className="label">{label}</span><input className="input" required={label === 'Viajante'} type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label> }
function Select({ value, onChange, compact }: { value: string; compact?: boolean; onChange: (value: string) => void }) { return <label>{!compact ? <span className="label">Status</span> : null}<select className={compact ? 'badge badge-blue border-0' : 'input'} value={value} onChange={(e) => onChange(e.target.value)}>{statuses.map((s) => <option key={s} value={s}>{s}</option>)}</select></label> }
