import { useState, type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { Plus, Trash2 } from 'lucide-react'
import { useBilling } from '@/hooks/useTransversal'
import { formatCurrency } from '@/lib/utils'
import type { BillingItem, CreateBillingInput } from '@/types'

const statuses: BillingItem['status'][] = ['pendente', 'faturado', 'pago', 'cancelado']

export default function BillingPage() {
  const { projectId } = useParams()
  const { items, total, paid, pending, isLoading, create, update, remove } = useBilling(projectId)
  const [draft, setDraft] = useState<Partial<CreateBillingInput>>({ status: 'pendente', currency: 'BRL', amount: 0 })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); create.mutate({ milestone: draft.milestone ?? '', amount: Number(draft.amount ?? 0), currency: draft.currency ?? 'BRL', due_date: draft.due_date, status: draft.status ?? 'pendente', notes: draft.notes }, { onSuccess: () => setDraft({ status: 'pendente', currency: 'BRL', amount: 0 }) }) }
  return <div className="mx-auto max-w-7xl px-6 py-8"><header className="mb-6"><span className="badge badge-blue">Módulo transversal</span><h1 className="mt-3 text-2xl font-bold text-text-primary">Faturamento</h1></header><section className="mb-5 grid gap-4 md:grid-cols-3"><Kpi label="Total" value={formatCurrency(total)} /><Kpi label="Pago" value={formatCurrency(paid)} /><Kpi label="Pendente" value={formatCurrency(pending)} /></section><form className="card mb-5" onSubmit={submit}><div className="grid gap-4 md:grid-cols-6"><Input label="Marco" value={draft.milestone ?? ''} onChange={(milestone) => setDraft((d) => ({ ...d, milestone }))} /><Input label="Valor" type="number" value={String(draft.amount ?? 0)} onChange={(amount) => setDraft((d) => ({ ...d, amount: Number(amount) }))} /><Input label="Vencimento" type="date" value={draft.due_date ?? ''} onChange={(due_date) => setDraft((d) => ({ ...d, due_date }))} /><Select value={draft.status ?? 'pendente'} onChange={(status) => setDraft((d) => ({ ...d, status: status as BillingItem['status'] }))} /><Input label="Notas" value={draft.notes ?? ''} onChange={(notes) => setDraft((d) => ({ ...d, notes }))} /><button className="btn-primary self-end" type="submit"><Plus className="h-4 w-4" /> Criar</button></div></form><section className="card overflow-hidden p-0">{isLoading ? <div className="p-6 text-text-secondary">Carregando...</div> : <table className="data-table"><thead><tr><th>Marco</th><th>Valor</th><th>Vencimento</th><th>Fatura</th><th>Pagamento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td className="text-text-primary">{item.milestone}</td><td>{formatCurrency(item.amount, item.currency)}</td><td>{item.due_date ?? '-'}</td><td>{item.invoice_date ?? '-'}</td><td>{item.payment_date ?? '-'}</td><td><Select compact value={item.status} onChange={(status) => update.mutate({ itemId: item.id, input: { status: status as BillingItem['status'] } })} /></td><td><button className="btn-danger btn-sm" type="button" onClick={() => remove.mutate(item.id)}><Trash2 className="h-3.5 w-3.5" /></button></td></tr>)}</tbody></table>}</section></div>
}
function Kpi({ label, value }: { label: string; value: string }) { return <div className="card2"><span className="text-sm text-text-secondary">{label}</span><strong className="mt-2 block text-xl text-text-primary">{value}</strong></div> }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; type?: string; onChange: (value: string) => void }) { return <label><span className="label">{label}</span><input className="input" required={label === 'Marco'} type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label> }
function Select({ value, onChange, compact }: { value: string; compact?: boolean; onChange: (value: string) => void }) { return <label>{!compact ? <span className="label">Status</span> : null}<select className={compact ? 'badge badge-blue border-0' : 'input'} value={value} onChange={(e) => onChange(e.target.value)}>{statuses.map((s) => <option key={s} value={s}>{s}</option>)}</select></label> }
